---
abstract: 'Interface to Tesco API'
author:
  - 'Dave Hodgkinson <davehodg@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-Tesco
requires:
  JSON: '1'
  LWP::Simple: '1'
  Pod::Coverage: '0'
  Test::More: '0'
  Test::Pod: '0'
  Test::Pod::Coverage: '0'
version: '0.1'
